name: Build GUI exe with Pyinstaller

#on:
#  release:
#    types: [created]
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
        
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

<<<<<<< HEAD
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
=======
    - uses: actions/upload-artifact@v2
      with:
        name: Acio_windows
        path: dist/windows
>>>>>>> d9a00df3b066e6cf8f8703ecd19cc02a5407a3c9

    - name: build with pyinstaller
      run: |
        pyinstaller --onefile src/build.spec

    - uses: actions/upload-artifact@v2
      with:
<<<<<<< HEAD
        name: Acio
        path: dist/windows
=======
        name: Acio_linux
        path: dist/linux
>>>>>>> d9a00df3b066e6cf8f8703ecd19cc02a5407a3c9
